version: "2"
services:
  svc-aggregator:
    build:
      context: ./svc-aggregator
      args:
        COLLECTOR_IP: 10.63.68.44
    image: svc-aggregator/consul
    container_name: hotel-aggregator
    networks:
      - hotelstack_hotel
    external_links:
      - zipkin:zipkin
    ports:
      - 10000:10000
      - 9999:9999
    environment:
      CONSUL_HOST: consul
  svc-details:
    build:
      context: ./svc-details
      args:
        COLLECTOR_IP: 10.63.68.44
    image: svc-details/consul
    container_name: hotel-details
    external_links:
      - zipkin:zipkin
    ports:
      - 10002:10002
    networks:
      - hotelstack_hotel
    environment:
      CONSUL_HOST: consul
  svc-pricing:
    build:
      context: ./svc-pricing
      args:
        COLLECTOR_IP: 10.63.68.44
    image: svc-pricing/consul
    container_name: hotel-pricing
    external_links:
      - zipkin
    ports:
      - 10003:10003
    networks:
      - hotelstack_hotel
    environment:
      CONSUL_HOST: consul
  svc-rating:
    build:
      context: ./svc-rating
      args:
        COLLECTOR_IP: 10.63.68.44
    image: svc-rating/consul
    container_name: hotel-rating
    external_links:
      - zipkin
    ports:
      - 10004:10004
    networks:
      - hotelstack_hotel
    environment:
      CONSUL_HOST: consul
  svc-availability:
    build:
      context: ./svc-availability
      args:
        COLLECTOR_IP: 10.63.68.44
    image: svc-availability/consul
    container_name: hotel-availability
    external_links:
      - zipkin
    ports:
      - 10001:10001
    networks:
      - hotelstack_hotel
    environment:
      CONSUL_HOST: consul

networks:
  hotelstack_hotel:
    external: true
