version: "2"
networks:
  hotel:

services:
  consul1:
    image: consul
    container_name: consul
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:8600/udp"
    networks:
      - hotel
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: 'consul-log'
