version: "2"
services:
  svc-aggregator:
    build: 
      context: ./svc-aggregator
#    container_name: aggregator
    links:
      - zipkin
    ports:
      - 10000:10000
      - 9999:9999
  svc-details:
    build: 
      context: ./svc-detail
#    container_name: hotel-details
    links:
      - svc-aggregator
      - zipkin
    ports:
      - 10002:10002
#  svc-pricing:
#    build: svc-pricing/.
#    links:
#      - hotel-aggregator
#      - zipkin
#  svc-rating:
#    build: svc-rating/.
#    links:
#      - svc-aggregator
#      - zipkin
#  svc-availability:
#    build: svc-availability/.
#    links:
#      - svc-aggregator
#      - zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9410:9410
      - 9411:9411