info:
  component: Hotel Rating

eureka:
  instance:
#    metadataMap:
#      cluster: hyatt
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:7979/eureka/
      
server:
#  port: 10000
  port: 0

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.netflix: DEBUG

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true