global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']
    - job_name: 'hotel'
      consul_sd_configs:
        - server: 'consul:8500'
          services: ['svc-aggregator', 'svc-details', 'svc-pricing', 'svc-availability', 'svc-rating']
      metrics_path: '/prometheus'
      relabel_configs:
       - source_labels: [ '__meta_consul_service' ]
         regex: '(.*)'
         target_label: 'instance'
         replacement: '$1'
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['node-exporter:9100']
