version: "2.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    networks:
      - hotelstack_hotel
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://localhost:9200']

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.0
    container_name: logstash
    ports:
      # Beats input -- https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-beats.html
      - 5044:5044
      # UDP input -- https://www.elastic.co/guide/en/logstash/master/plugins-inputs-udp.html#plugins-inputs-udp-codec
      - 43448:43448/udp
      # Monitoring APIs -- https://www.elastic.co/guide/en/logstash/5.0/monitoring.html
      - 9600:9600
      # GELF input
      - 12201:12201/udp
    volumes:
      - ./elk/:/usr/share/logstash/pipeline/
#        - ./elk/:/usr/share/logstash/config/
    links:
      - elasticsearch
    networks:
      - hotelstack_hotel

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
        - 5601:5601
    networks:
      - hotelstack_hotel
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601/login']

  filebeat:
    image: docker.elastic.co/beats/filebeat:5.3.0
    group_add: ['root', 'adm']
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    # volumes: ['/var/log:/mnt/log:ro']
    networks:
      - hotelstack_hotel
    depends_on:
      elasticsearch:
        condition: service_healthy
volumes:
  esdata:
    driver: local

networks:
  hotelstack_hotel:
    external: true
